// Generated by CoffeeScript 1.4.0
(function() {
  var pizza;

  pizza = {
    toppings: ['cheese', 'sauce', 'pepperoni'],
    crust: 'deep dish',
    serves: 2
  };

  console.log(pizza);

}).call(this);
