// Generated by CoffeeScript 1.4.0
(function() {
  var parsePromised, q;

  q = require('q');

  parsePromised = function(json) {
    var defer, result;
    defer = q.defer();
    try {
      result = JSON.parse(json);
    } catch (e) {
      defer.reject(e);
    }
    defer.resolve(result);
    return defer.promise;
  };

  parsePromised(process.argv[2]).then(null, console.log);

}).call(this);
