// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(messages) {
    if (messages == null) {
      messages = [];
    }
    return messages.filter(function(item) {
      return item.message.length < 50;
    }).map(function(item) {
      return item.message;
    });
  };

}).call(this);
