// Generated by CoffeeScript 1.4.0
(function() {
  var machine, robby, robot;

  machine = {
    motors: 4
  };

  robot = {
    friendly: true
  };

  robby = {};

  robot.__proto__ = machine;

  robby.__proto__ = robot;

  claim(robby.motors, 4);

  claim(robby.friendly, true);

  module.exports = {
    machine: machine,
    robot: robot,
    robby: robby
  };

}).call(this);
