// Generated by CoffeeScript 1.4.0
(function() {
  var i, limit, total, _i;

  total = 0;

  limit = 10;

  for (i = _i = 0; 0 <= limit ? _i < limit : _i > limit; i = 0 <= limit ? ++_i : --_i) {
    total += i;
  }

  console.log(total);

}).call(this);
