// Generated by CoffeeScript 1.4.0
(function() {
  var curry;

  curry = function(fn, n) {
    n = n || fn.length;
    return function(arg) {
      if (!(--n > 0)) {
        return fn(arg);
      }
      return curry(fn.bind(fn, arg), n);
    };
  };

  module.exports = curry;

}).call(this);
