// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(tree) {
    var getDeps, output;
    output = [];
    (getDeps = function(subtree) {
      if (subtree.dependencies !== void 0) {
        return Object.keys(subtree.dependencies).forEach(function(dep) {
          var version;
          version = "" + dep + "@" + subtree.dependencies[dep].version;
          if (output.indexOf(version) === -1) {
            output.push(version);
          }
          return getDeps(subtree.dependencies[dep]);
        });
      }
    })(tree);
    return output.sort();
  };

}).call(this);
