// Generated by CoffeeScript 1.4.0
(function() {
  var http;

  http = require('q-io/http');

  http.read('http://localhost:7000').then(function(id) {
    return http.read("http://localhost:7001/" + (id.toString())).then(function(data) {
      return console.log(JSON.parse(data.toString())).then(null, console.error).done();
    });
  });

}).call(this);
