// Generated by CoffeeScript 1.4.0
(function() {
  var iterate, q, throwMyGod;

  q = require('q');

  throwMyGod = function() {
    throw new Error('OH NOES');
  };

  iterate = function(number) {
    console.log(number);
    return ++number;
  };

  q.fcall(iterate, 1).then(iterate).then(iterate).then(iterate).then(iterate).then(throwMyGod).then(iterate).then(iterate).then(iterate).then(iterate).then(null, throwMyGod).done(null, console.log);

}).call(this);
