// Generated by CoffeeScript 1.4.0
(function() {
  var Robot;

  Robot = Object.create;

  Robot["new"] = function() {
    return Object.create(this);
  };

  module.exports = {
    Robot: Robot
  };

}).call(this);
