// Generated by CoffeeScript 1.4.0
(function() {
  var machine, robot, vehicle;

  machine = {};

  vehicle = {};

  robot = {};

  vehicle.__proto__ = machine;

  robot.__proto__ = machine;

  claim(vehicle.motors, void 0);

  claim(robot.motors, void 0);

  machine.motors = 4;

  claim(vehicle.motors, 4);

  claim(robot.motors, 4);

  module.exports = {
    machine: machine,
    vehicle: vehicle,
    robot: robot
  };

}).call(this);
