// Generated by CoffeeScript 1.4.0
(function() {
  var attachTitle, defer, q;

  q = require('q');

  defer = q.defer();

  attachTitle = function(name) {
    return "DR. " + name;
  };

  defer.promise.then(attachTitle).then(console.log);

  defer.resolve('MANHATTAN');

}).call(this);
