// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(target, method) {
    var orig, thiss;
    orig = target[method];
    thiss = this;
    this.count = 0;
    target[method] = function() {
      thiss.count++;
      return orig.apply(target, arguments);
    };
    return this;
  };

}).call(this);
