// Generated by CoffeeScript 1.4.0
(function() {
  var machine, robby, robot;

  machine = {};

  robot = Object.create(machine);

  robby = Object.create(robot);

  claim(machine.isPrototypeOf(robby), true);

  claim(robot.isPrototypeOf(robby), true);

  claim.same(Object.getPrototypeOf(robby), robot);

  module.exports = {
    machine: machine,
    robot: robot,
    robby: robby
  };

}).call(this);
