// Generated by CoffeeScript 1.4.0
(function() {
  var Robot, Vehicle;

  Robot = function() {};

  Vehicle = function() {
    return {};
  };

  module.exports = {
    Robot: Robot,
    Vehicle: Vehicle
  };

}).call(this);
