// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function() {
    return Array.prototype.slice.call(arguments).filter(function(object) {
      return Object.prototype.hasOwnProperty.call(object, 'quack');
    }).length;
  };

}).call(this);
