// Generated by CoffeeScript 1.4.0
(function() {
  var defer, q;

  q = require('q');

  defer = q.defer();

  defer.promise.then(console.log, console.log);

  defer.resolve('I FIRED');

  defer.reject('I DID NOT FIRE');

}).call(this);
