// Generated by CoffeeScript 1.4.0
(function() {
  var defer, printError, q;

  q = require('q');

  defer = q.defer();

  printError = function(err) {
    return console.log(err.message);
  };

  defer.promise.then(null, printError);

  setTimeout(defer.reject, 300, new Error('REJECTED!'));

}).call(this);
