// Generated by CoffeeScript 1.4.0
(function() {
  var repeat, trampoline;

  repeat = function(operation, num) {
    return function() {
      if (num <= 0) {
        return false;
      }
      operation();
      return repeat(operation, --num);
    };
  };

  trampoline = function(fn) {
    var _results;
    _results = [];
    while (fn !== false) {
      _results.push(fn = fn());
    }
    return _results;
  };

  module.exports = function(operation, num) {
    return trampoline(repeat(operation, num));
  };

}).call(this);
